### ISSUE TITLE
被静默后，显示群聊黑名单数量错误

### ISSUE THREAD

**Issue by Agnes4m** [tkgs0/nonebot-plugin-blacklist#1]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](https://github.com/tkgs0/nonebot-plugin-blacklist/issues) 中没有相同或相似的问题。

### blacklist

0.3.3

### go-cqhttp

1.0.1

### nonebot

2.0.0rc4

### Python

3.10.6

### 操作系统

ubuntu22.04

### 列出安装的 Python 包

pip 安装

### 问题描述

群聊数量显示错误

### 复现步骤

- 被禁言
- 使用指令`查看群聊黑名单`

### 期望行为

正常显示两行

### 实际行为

把auto_sleep也算金金金金金了群聊数量

### 日志信息

![image](https://github.com/tkgs0/nonebot-plugin-blacklist/assets/70925546/9007bbf8-b8a6-43b8-9258-189b7623f627)

### 额外补充

None

**Comment by tkgs0** [comment]
咕咕咕, 下一个版本修

**Comment by tkgs0** [comment]
已修, 版本更新 `0.3.4`
