### ISSUE TITLE
正常安装插件后无法运行

### ISSUE THREAD

**Issue by RyanJiang184** [tkgs0/nonebot-plugin-blacklist#2]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](https://github.com/tkgs0/nonebot-plugin-blacklist/issues) 中没有相同或相似的问题。

### blacklist

0.3.5

### go-cqhttp

未使用go-cqhttp，使用其它ws

### nonebot

2.0.0

### Python

3.8.5

### 操作系统

Windows Server 2012 R2 Datacenter

### 列出安装的 Python 包

nb安装

### 问题描述

正常安装插件后启动报错

### 复现步骤

nb plugin install .....
nb run
报错

### 期望行为

正常运行

### 实际行为

报错

### 日志信息

![CH)%A6U31G @(VN$~38{7D8](https://github.com/tkgs0/nonebot-plugin-blacklist/assets/111217394/95cf7f4c-be9a-406b-b112-46c9dacbb94a)

**Comment by RyanJiang184** [comment]
已经解决，判断为使用了其它ws导致无法实现某些功能的原因。注释掉部分代码后插件成功运行。
![HRYIW L`I D)%YH` XC(R P](https://github.com/tkgs0/nonebot-plugin-blacklist/assets/111217394/3d65c518-b580-4a85-83a8-7903ffca7990)

**Comment by tkgs0** [comment]
目前只兼容onebot v11标准
