### ISSUE TITLE
让每个bot可以单独拉黑群

### ISSUE THREAD

**Issue by ABKQPO** [tkgs0/nonebot-plugin-blacklist#3]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](https://github.com/tkgs0/nonebot-plugin-blacklist/issues) 中没有相同或相似的需求。
- [ ] 我有足够的时间和能力，愿意为此提交 [PR](https://github.com/tkgs0/nonebot-plugin-blacklist/pulls) 来实现功能。

### 您希望能解决什么样的问题？

bot1和bot2在同一群，让bot1拉黑群bot2不受影

### 您想要的解决方案

bot1和bot2在同一群，让bot1拉黑群bot2不受影响

**Comment by tkgs0** [comment]
Good idea! 但本人精力有限, 近期可能没空, 预计最晚明年端阳之前实现

**Comment by ABKQPO** [comment]
可以通过识别bot的selfid实现

**Comment by herobrinein** [comment]
能否在被禁言的时候显示执行禁言的账号

**Comment by tkgs0** [comment]
> 能否在被禁言的时候显示执行禁言的账号

已修, 更新版本 `0.3.7` , 多Bot分别设置黑名单还在努力实现中(~还没开始写~)

**Comment by tkgs0** [comment]
已更新, 发布版本 [1.0.0](https://github.com/tkgs0/nonebot-plugin-blacklist/releases/tag/1.0.0)
