### ISSUE TITLE
静默和响应多加了个/

### ISSUE THREAD

**Issue by ABKQPO** [tkgs0/nonebot-plugin-blacklist#4]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](https://github.com/tkgs0/nonebot-plugin-blacklist/issues) 中没有相同或相似的问题。

### blacklist

。

### go-cqhttp

.

### nonebot

.

### Python

.

### 操作系统

.

### 问题描述

,

### 复现步骤

.

### 实际行为

.

### 日志信息

.

**Comment by tkgs0** [comment]
看你自己的设置,
`.env` 里 `COMMAND_START` 填的 `[""]` 就是 `/响应`,
填的 `["/"]` 就是 `//响应`,
填写 `["", "/"]` 就 `/响应` `//响应` 都会响应

**Comment by tkgs0** [comment]
如果你的意思是只要 `响应` 两个字就响应, 不加前面的 `/`, 请自行修改代码然后装到你的Bot上
