### ISSUE TITLE
能否把全体禁言和单独禁言分开，加入指定账号被禁言时拉黑

### ISSUE THREAD

**Issue by ABKQPO** [tkgs0/nonebot-plugin-blacklist#5]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](https://github.com/tkgs0/nonebot-plugin-blacklist/issues) 中没有相同或相似的需求。
- [ ] 我有足够的时间和能力，愿意为此提交 [PR](https://github.com/tkgs0/nonebot-plugin-blacklist/pulls) 来实现功能。

### 您希望能解决什么样的问题？

如标题所示，目前无法区分全体禁言和单独被禁言

### 您想要的解决方案

区分开两种事件，加入指定账号被禁言拉黑，例如Superuser等等，可以自定义（白名单）

**Comment by tkgs0** [comment]
请选择issue `问题回报` 上报问题并提供复现截图
